apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-ingress
  namespace: test
spec:
  ingressClassName: nginx
  rules:
    - host: "hello-world.com"
      http:
        paths:
          - path: /helloWorld
            pathType: Prefix
            backend:
              service:
                name: hello-world-service
                port:
                  number: 80