apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "hello-world.fullname" . }}-network-policy
  labels:
  {{- include "hello-world.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: hello-world
  policyTypes:
  - Ingress
  - Egress
