apiVersion: v1
kind: ConfigMap
metadata:
  name: json-configmap
  namespace: test
data:
  config.json: |
    {
      "users": [
        {
          "id": 1,
          "name": "Alice Johnson",
          "email": "alice.johnson@example.com",
          "isActive": true
        },
        {
          "id": 2,
          "name": "Bob Smith",
          "email": "bob.smith@example.com",
          "isActive": false
        },
        {
          "id": 3,
          "name": "Charlie Brown",
          "email": "charlie.brown@example.com",
          "isActive": true
        }
      ]
    }

